using System;
using Silverfly.Text;

namespace Silverfly;

/// <summary>
/// A simple token class. These are generated by <see cref="Lexer"/>
/// and consumed by <see cref="Parser"/>.
/// </summary>
public struct Token(Symbol type, ReadOnlyMemory<char> text, int line, int column)
{
    public static Token Invalid(char c, int line, int column) => new("#invalid", c.ToString().AsMemory(), line, column);

    public Symbol Type { get; } = type;

    public ReadOnlyMemory<char> Text { get; set; } = text;

    public int Line { get; } = line;

    public int Column { get; } = column;

    public SourceDocument Document { get; set; }

    public Token(Symbol type, int line, int column)
    : this(type, type.Name.AsMemory(), line, column)
    {
    }

    public override readonly string ToString() => Text.ToString();

    public readonly SourceSpan GetSourceSpanStart() => new(Line, Column);

    public readonly SourceSpan GetSourceSpanEnd() => new(Line, Column + Text.Length - 1);

    public Token WithDocument(SourceDocument document)
    {
        Document = document;

        return this;
    }

    public readonly SourceRange GetRange() => new(Document, GetSourceSpanStart(), GetSourceSpanEnd());

    public static bool operator ==(Token left, Token right) => left.Equals(right);

    public static bool operator !=(Token left, Token right) => !left.Equals(right);

    public override readonly bool Equals(object obj) => base.Equals(obj);

    public override readonly int GetHashCode() => base.GetHashCode();
}
